import forms from "@tailwindcss/forms";
import containerQueries from "@tailwindcss/container-queries";

/** @type {import('tailwindcss').Config} */
const config = {
  darkMode: "class",
  content: ["./src/**/*.{js,jsx,mjs}"],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e1e3e1",
        "surface-dim": "#d8dad9",
        "on-primary-container": "#a9eebf",
        "surface-bright": "#f8faf8",
        "secondary-fixed-dim": "#8cd6a9",
        "on-surface-variant": "#404942",
        "on-surface": "#191c1b",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        "on-background": "#191c1b",
        "surface-tint": "#286a46",
        "primary-fixed": "#adf2c3",
        "inverse-on-surface": "#eff1ef",
        "secondary-fixed": "#a7f3c3",
        "secondary-container": "#a7f3c3",
        "error": "#ba1a1a",
        "outline-variant": "#bfc9bf",
        "on-tertiary-container": "#ffd3d6",
        "tertiary-fixed-dim": "#ffb2b9",
        "outline": "#707971",
        "surface": "#f8faf8",
        "on-tertiary-fixed-variant": "#73323b",
        "on-secondary-fixed": "#002111",
        "secondary": "#1e6b46",
        "primary": "#0d5533",
        "on-tertiary-fixed": "#3b0612",
        "tertiary-fixed": "#ffdadc",
        "surface-container-highest": "#e1e3e1",
        "primary-container": "#2c6e49",
        "surface-container": "#eceeec",
        "on-primary-fixed-variant": "#065230",
        "on-primary": "#ffffff",
        "on-secondary-container": "#26714b",
        "surface-container-high": "#e6e9e7",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#92d5a8",
        "primary-fixed-dim": "#92d5a8",
        "tertiary-container": "#944c55",
        "background": "#f8faf8",
        "inverse-surface": "#2e3130",
        "on-secondary-fixed-variant": "#005231",
        "surface-container-low": "#f2f4f2",
        "on-primary-fixed": "#002110",
        "tertiary": "#77353e",
      },
      fontFamily: {
        headline: ["var(--font-manrope)", "system-ui", "sans-serif"],
        body: ["var(--font-manrope)", "system-ui", "sans-serif"],
        label: ["var(--font-manrope)", "system-ui", "sans-serif"],
        manrope: ["var(--font-manrope)", "system-ui", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [forms, containerQueries],
};

export default config;
