import type { Config } from 'tailwindcss'

const config: Config = {
  content: ['./app/**/*.{ts,tsx}', './components/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#2C6E49',
        secondary: '#4C956C',
        surface: '#F9FAF9',
        'on-surface': '#1A1C1A',
        'surface-container': '#F2F4F2',
        outline: '#717971',
        error: '#BA1A1A',
        'on-primary': '#ffffff',
        'primary-container': '#2c6e49',
        'secondary-container': '#a7f3c3',
        'on-surface-variant': '#404942',
        'outline-variant': '#bfc9bf',
        'surface-container-low': '#f2f4f2',
        'surface-container-high': '#e6e9e7',
        'surface-container-highest': '#e1e3e1',
        'surface-container-lowest': '#ffffff',
        'on-secondary-container': '#26714b',
        'surface-bright': '#f8faf8',
        'surface-dim': '#d8dad9',
        'inverse-surface': '#2e3130',
        'inverse-on-surface': '#eff1ef',
        'inverse-primary': '#92d5a8',
        'secondary-fixed': '#a7f3c3',
        'secondary-fixed-dim': '#8cd6a9',
        'on-secondary-fixed': '#002111',
        'on-secondary-fixed-variant': '#005231',
        'primary-fixed': '#adf2c3',
        'primary-fixed-dim': '#92d5a8',
        'on-primary-fixed': '#002110',
        'on-primary-fixed-variant': '#065230',
        'on-primary-container': '#a9eebf',
        'surface-tint': '#286a46',
        'surface-variant': '#e1e3e1',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'on-background': '#191c1b',
        background: '#f8faf8',
        tertiary: '#77353e',
        'tertiary-container': '#944c55',
        'tertiary-fixed': '#ffdadc',
        'tertiary-fixed-dim': '#ffb2b9',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#ffd3d6',
        'on-tertiary-fixed': '#3b0612',
        'on-tertiary-fixed-variant': '#73323b',
        'on-secondary': '#ffffff',
      },
      fontFamily: {
        sans: ['Manrope', 'sans-serif'],
        manrope: ['Manrope', 'sans-serif'],
        headline: ['Manrope', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}

export default config
